name: Test, Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Chrome para Karma en modo headless
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run unit tests (headless)
        env:
          CHROME_BIN: chrome
        run: npm run test:ci

      - name: Build Angular (prod)
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          npx ng build --configuration=production --base-href "/${REPO_NAME}/"

      - name: Detect output folder
        id: detect
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const aj = JSON.parse(fs.readFileSync('angular.json','utf8'));
          const proj = Object.keys(aj.projects)[0];
          const targets = aj.projects[proj].targets || aj.projects[proj].architect;
          const out = targets.build.options.outputPath;
          const final = fs.existsSync(out + '/browser') ? (out + '/browser') : out;
          require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `path=${final}\n`);
          NODE

      - name: Add SPA 404.html
        run: cp "${{ steps.detect.outputs.path }}/index.html" "${{ steps.detect.outputs.path }}/404.html"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.detect.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
